name: 10fastfingers enter retest Bug Report
description: Report an issue for the 10fastfingers enter retest userscript
title: "[10fastfingers] [enter_retest] "
labels: ["bug"]
body:
  - type: input
    id: script_version
    attributes:
      label: Script Version
      description: What version of the script are you using?
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue here...
    validations:
      required: true
