name: ChatGPT Prompt Queue Bug Report
description: Report an issue for the ChatGPT Prompt Queue userscript
title: "[AI_Queue] [ChatGPT Prompt Queue] "
labels: ["bug"]
body:
  - type: input
    id: script_version
    attributes:
      label: Script Version
      description: What version of the script are you using?
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue here...
    validations:
      required: true
