name: Google Forms Saver Bug Report
description: Report an issue for the Google Forms Saver userscript
title: "[Google Forms] [Google Forms Saver] "
labels: ["bug"]
body:
  - type: input
    id: script_version
    attributes:
      label: Script Version
      description: What version of the script are you using?
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue here...
    validations:
      required: true
