name: Pixabay Hide AI Bug Report
description: Report an issue for the Pixabay Hide AI userscript
title: "[Pixabay] [Hide AI] "
labels: ["bug"]
body:
  - type: input
    id: script_version
    attributes:
      label: Script Version
      description: What version of the script are you using?
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue here...
    validations:
      required: true
